# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

 flutter_application_path = '/Users/xionghao/Documents/Flutter/iOS/my_flutter/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

target 'flutter_mixed' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for flutter_mixed

end
